name: Test React App
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repitory code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test app
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get the repitory code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: lint application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repitory code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: build application
        run: npm run build
